### ISSUE TITLE
503 Service Unavailable on docker pull

### ISSUE THREAD

**Issue by georgecookeIW** [triggermesh/knative-local-registry#13]
**Platform Details**
MacOSX 10.14.6
Docker for Desktop (running Kubernetes) 18.01+
daemon.json (insecure registry added)
`{
  "insecure-registries" : [
    "knative.registry.svc.cluster.local",
    "kanikocache.registry.svc.cluster.local",
    "builds.registry.svc.cluster.local",
  ],
  "debug" : true,
  "experimental" : false
}`

**Issue Details**
I am trying to get a knative-service running with this local-registry, but keep getting revision failures with the error 'container-missing'. At this point, i fell back onto the test files provided in the repo; I can push an image to the registry from within a Kubernetes pod in the cluster. But I am unable to pull an image from the registry using docker pull / the test Job provided.
Error: _Error response from daemon: received unexpected HTTP status: 503 Service Unavailable_

Image push (kaniko-push.yaml) works fine and I can see the image in the registry (Alpine:3.7 test pod):
`/ # curl http://knative.registry.svc.cluster.local/v2/_catalog`
`{"repositories":["registrytest/kanikopush"]}`

From the host-docker-pull.yaml Job:
`$ kubectl logs pod/docker-pull-79vrz -n registry`
`Error response from daemon: received unexpected HTTP status: 503 Service Unavailable`

And using docker pull (Alpine:3.7 test pod):
`/ # docker pull knative.registry.svc.cluster.local/registrytest/kanikopush:latest`
`FATA[0015] Error response from daemon: received unexpected HTTP status: 503 Service Unavailable`

**Sysadmin solution**
As per suggestion if pull fails, sysadmin solution was installed and is working:
`$ kubectl -n kube-system logs -l app=registry-etc-hosts-update -c update`
`--- /host-etc/hosts     2017-04-18 16:30:00.000000000 +0000
+++ -   2019-08-15 10:27:02.782185442 +0000
@@ -4,3 +4,6 @@
 ff00::0 ip6-mcastprefix
 ff02::1 ip6-allnodes
 ff02::2 ip6-allrouters
+10.110.130.102  knative.registry.svc.cluster.local
+10.105.123.119  builds.registry.svc.cluster.local
+10.106.244.132  kanikocache.registry.svc.cluster.local`

`$ kubectl -n registry get service knative -o jsonpath='{.spec.clusterIP}'`
`10.110.130.102`

**Some additional info**
Some of the issues online re. the 503 are related to not having the insecure registry configured, but I have it correctly applied in the daemon.json (as far as I can tell). I was getting the old _server gave HTTP response to HTTPS client_ error before adding the FQDN of the registry to insecure-registries.
I did find this issue: https://github.com/docker/for-linux/issues/180 but it is specifically for Linux and don't think MacOSX uses systemd at all anyway.
There is also this, directly related to MacOSX https://github.com/docker/for-mac/issues/2897 but it appears to be an issue with a remote registry rather than a local private registry.

I can see that the docker pull request does not appear to hit the registry pod at all, as I would expect to see a 503 logged in the pod logs: (this is taken just after executing docker pull in a test pod):
`$ kubectl logs registry-h9k25 -n registryz`
`10.1.0.1 - - [15/Aug/2019:11:15:20 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.14"
10.1.0.1 - - [15/Aug/2019:11:15:30 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.14"
10.1.0.1 - - [15/Aug/2019:11:15:39 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.14"
10.1.0.1 - - [15/Aug/2019:11:15:49 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.14"`

**Note**
I am running the registry and Jobs in a namespace called _registry_.
The Alpine:3.7 test pod I reference is running in the _default_ namespace.
As I understand it the namespace should plays no part in the resolution of the registry service.

Any thoughts on why this is generating a 503 error?

**Comment by solsson** [comment]
If you applied the yamls from current master there's really nothing there that can produce a 503, unless the registry itself does it. I think you can experiment with that by switching the `docker-v2` container over to for example an `nginx` image.

So we'd have to  follow the name resolution to try to see who's responding. Unfortunately the errors don't log the resolved IP. Should be `10.110.130.102`. I haven't been running Docker for Mac's k8s, but can you try curl inside the vm for example? The /etc/hosts update from within a pod is far from conventional, so maybe it has no actual effect on image pull? Maybe it hits an ingress? Is docker for mac using Dockerd or Containerd? With  Containerd I've had to switch to http even if the address is .local, for example https://github.com/rancher/k3s/issues/145#issuecomment-520737661. However those errors tend to complain about SSL certificate validity instead.

**Comment by georgecookeIW** [comment]
Docker for Mac uses dockerd.

Good point about the ingress, I am running Istio (which controls ingress into the k8s cluster on localhost:80, localhost:443 etc...) so its very possible that the istio-ingress-controller is taking over and routing the request into the k8s services looking for a VirtualService that matches the /registrytest/kanikopush URI. However when I `curl` to the registry I don't get back any Host header in the response specifying istio as the response host, which suggests the istio-ingress-controller is not the one sending the 503 back.

I did try switching ports from 80 (in the templates/*.yaml files) over to port 45000 (currently empty port in the k8s cluster) and that also had no effect; same results. (not too surprising)

I'll replace the `docker-v2` with `nginx` image and see what happens. I am also going to try recreate the manifest and layer requests that `docker pull` does under-the-hood to see if I can manually pull an image from the repository inside a pod; at the very least this should bypass any potential DNS issues and give me some logs in the registry pod.

In terms of the /etc/hosts update, I have seen the DaemonSet job add new IP addresses for the knative DNS record when I restart, but that only implies its working as expected. I am wondering if its something to do with my own Docker Daemon, since the host-docker-pull.yaml does volume mount the docker.sock from my host machine.

Thanks for the suggestions, I'll let you know what I find.

**Comment by georgecookeIW** [comment]
Bit more info; I hooked into the Docker Daemon logs and got this:
`2019-08-15 16:08:49.294259+0100 localhost com.docker.vpnkit[5329]: DNS lookup knative.registry.svc.cluster.local A: Timeout` 
`2019-08-15 16:08:49.294313+0100 localhost com.docker.vpnkit[5329]: HTTP proxy: returning 503 Service_unavailable`

**DNS lookup knative.registry.svc.cluster.local A: Timeout**
So possibly an issue in `coredns` that Docker for Mac is using to run the k8s cluster.

**Comment by solsson** [comment]
Ok so it's unaffected by the host file update. When you're looking for solution, know that the hosts file update is a hack :) Any other hack is allowed. Doesn't have to be name resolution. The only objective is to be able to use the same image URLs in containers (knative specifically) as when starting pods. For example the Containerd alias mechanism I mentioned could be used to set the ClusterIP of the service. Maybe Dockerd has similar configuration. The problem with such an approach might be that it requires daemon restart.

**Comment by georgecookeIW** [comment]
I managed to trace the DNS lookup issue back to the hosts file on my machine.

In short, the update to the `/etc/hosts` file was not taking effect on my Host at all. This means the `docker pull` was trying to find `knative.registry.svc.cluster.local` outside of the cluster. Which explains why the registry didn't report the 503 in its logs.

Solution was very simple (in order to keep the knative.registry.svc.cluster.local host in the files and use it in a knative service):

Edit `/etc/hosts` on the Docker Host machine and add:
`127.0.0.1 knative.registry.svc.cluster.local`

I can now pull and push images correctly to the local k8s registry.
NOTE: I think this issue is specific to a Docker for Desktop hosted k8s cluster.

Thanks for your help on this @solsson
